alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: docker-react
region: fra
services:
- name: webapp
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  image:
    registry_type: DOCR
    repository: docker-react
    tag: latest