alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: docker-react
region: fra
services:
- name: webapp
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  image:
    registry_type: DOCR
    repository: dnw2022
    tag: docker-react-latest
  # note that digital ocean does NOT currently support pulling private images from docker hub
  # image:
  #   registry: dnw2022
  #   registry_type: DOCKER_HUB
  #   repository: docker-react
  #   tag: latest